### ISSUE TITLE
Can electron be compatible?

### ISSUE THREAD

**Issue by hm-lee** [mlynch/nextjs-tailwind-ionic-capacitor-starter#11]
Hello, first of all, thank you for the good template!
Is it possible to export nextjs for electron? 👀
It is quite impressive that this template uses capacitorjs.

How about supporting mobile and PC at the both time?

**Comment by hm-lee** [comment]
Oh... it already exists in capacitorjs...!
https://capacitor-community.github.io/electron/#/./getting-started/index
```bash
npm i @capacitor-community/electron
npx cap add @capacitor-community/electron
npx cap open @capacitor-community/electron
```

**Comment by mlynch** [comment]
Awesome, let us know how it works.
