### ISSUE TITLE
404 issue with _next/static/chunks/*.js

### ISSUE THREAD

**Issue by hm-lee** [mlynch/nextjs-tailwind-ionic-capacitor-starter#13]
<img width="808" alt="스크린샷 2021-02-25 오전 10 12 49" src="https://user-images.githubusercontent.com/69321331/109089491-b1455000-7754-11eb-8a32-cbf21d308d08.png">

<img width="454" alt="스크린샷 2021-02-25 오전 10 32 07" src="https://user-images.githubusercontent.com/69321331/109089538-c8843d80-7754-11eb-8ec7-a6e2a42d9fa5.png">

@mlynch 
It appears that the capacitorjs cannot recall script files located in this path when the folder depth is greater than 3. How can i solve this problem when i distribute it to Android?

**Comment by mlynch** [comment]
Can you try adding this line in your `app/build.gradle`? https://github.com/ionic-team/capacitor/blob/main/android-template/app/build.gradle#L15

**Comment by hm-lee** [comment]
I'm sorry for the late reply. It works perfectly.
I don't know the details of this option, but all the problems have been resolved. Thank you.

**Comment by mlynch** [comment]
You're saying my suggestion and adding that line fixed it @hm-lee?
