### ISSUE TITLE
Android Studio doesn't work - white screen

### ISSUE THREAD

**Issue by realmichaelye** [mlynch/nextjs-tailwind-ionic-capacitor-starter#17]
When I deploy to android studio it gives a white screen like this https://gyazo.com/7798fe638051a550a0df0f7d42e8a153

---
Spent time looking into this and I hypothesize it could have to do with the nextjs build/export not working by itself (can't just run index.html, have to spin up a server)?

This is the console when I open index.html on the /out/: https://gyazo.com/e021579caf3c4914ed109f80edf5407f
^npm run dev works & if I run the build with http-server works too

Note: no changes were made to the repo & ran the correct commands (npm run build, npm run export, npx cap copy, npx cap open android)

**Comment by Forpee** [comment]
Same issue

**Comment by Forpee** [comment]
Android Studio doesn't copy folders in assets that start with _.

So go into the config file at ./android/app/build.gradle 

then inside android -> defaultConfig add:
aaptOptions {
    ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~'
}

so it should look something like this: 

android {
    ...
    defaultConfig {
        ...
        aaptOptions {
            ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~'
        }
    }
}

**Comment by mlynch** [comment]
Thanks @Forpee this is the correct solution and is fixed in future versions of Capacitor's android template.
