### ISSUE TITLE
Using getStaticProps

### ISSUE THREAD

**Issue by Rijast** [mlynch/nextjs-tailwind-ionic-capacitor-starter#20]
Is there a way to use getStaticProps with this? I want to generate my pages statically using an API but as far as I can tell this will only work with nextjs if the pages I am generating via slugs are within the /pages directory with the [] syntax. Do you know an easy way I could accomplish this keeping the same structure you have or how it might need to be modified?

Thanks lot!

**Comment by AlexcastroDev** [comment]
> Is there a way to use getStaticProps with this? I want to generate my pages statically using an API but as far as I can tell this will only work with nextjs if the pages I am generating via slugs are within the /pages directory with the [] syntax. Do you know an easy way I could accomplish this keeping the same structure you have or how it might need to be modified?
> 
> Thanks lot!

I think getStaticProps works since it is not part of unsupported features: https://nextjs.org/docs/advanced-features/static-html-export#unsupported-features

But, idk how it works internally. Something broke ?

**Comment by mlynch** [comment]
`getStaticProps` should work just fine. You would create new pages in the root `pages` directory and then render that page tree from the top down. Right now there's a catch-all route that you would just remove or override for specific pages if you want to use `getStaticProps`
