### ISSUE TITLE
Auth0 Integration

### ISSUE THREAD

**Issue by patrick-ofallon** [mlynch/nextjs-tailwind-ionic-capacitor-starter#24]
I have been really enjoying the NextJS and Ionic integration.  So far it's very fast and impressive to be able to leverage strengths of NextJS and one framework.  The SSR and cross to native does seem to be the major obstacle to overcome.  As an example, I am utilizing Auth0 and things work great on everything Web.  However, callbacks and handoffs to the external API and back to the app seems to hold things back as Auth0 leverages the API in to accomplish this.

https://auth0.com/docs/quickstart/native/ionic-react/01-login

Yet - wondering if leveraging some of their Ionic React and native callbacks could help.  Does anyone have any advise on how to cross to native with Auth0 and NextJS using Ionic?

Thanks in advance.

**Comment by patrick-ofallon** [comment]
Follow-Up:  Auth0 working perfectly as expected on all Web PWA, still issues with Native.  Looking into Ionic's Auth Connect to resolve and unify native with Web.  https://ionic.io/docs/auth-connect/auth-connect-react

**Comment by AlexcastroDev** [comment]
> Follow-Up: Auth0 working perfectly as expected on all Web PWA, still issues with Native. Looking into Ionic's Auth Connect to resolve and unify native with Web. https://ionic.io/docs/auth-connect/auth-connect-react

I have so many troubles with React Ionic Auth0 integration.

So, instead using: buildAuthorizeUrl, i changed it to loginWithRedirect from useAuth0.
It's better use Native safari, instead Browser.open().

I intend to create a new boilerplate, with Capacitor 4 and Auth0 with NextJS and ReactJS. May it can help you as well.

**Comment by mlynch** [comment]
Won't be adding any specific auth integrations to keep this generic but if someone wants to maintain a fork they are more than welcome!
