### ISSUE TITLE
Ripple effect appears twice when click on a button on mobile

### ISSUE THREAD

**Issue by Toumani** [mlynch/nextjs-tailwind-ionic-capacitor-starter#26]
Don't know how to qualify this but it looks like a minor bug.

### How to reproduce

- npm run dev
- open project in a Chrome-based browser (I tried Chromium and Opera)
- Switch to mobile preview in DevTools
- Click on an item in the list tab : 

There are two ripples, one with primary color and the other in gray.

**Comment by mlynch** [comment]
Odd, will share with the team. Could be this is just using an older version of Ionic UI components and this has since been fixed.

**Comment by mlynch** [comment]
Closing as not related to this specific project
