### ISSUE TITLE
Capacitor V4 update

### ISSUE THREAD

**Issue by AliMejbar** [mlynch/nextjs-tailwind-ionic-capacitor-starter#30]

**Comment by MACscr** [comment]
No luck on this huh? I couldnt install a few of its dependencies either to even test it out.

**Comment by mlynch** [comment]
I haven't had time to migrate it. Would love a PR if anyone is able to give it a shot, otherwise it'll have to wait

**Comment by AlexcastroDev** [comment]
> I haven't had time to upgrade it. Would love a PR if anyone is able to give it a shot, otherwise it'll have to wait

Hi !!! I would love to open this PR.
I spend so many hours with integration Auth0 + Ionic + NextJS, and currently it's working like magic <3

BTW, if you allow me open this PR, i noticed thats not necessary to use Ionic Router ( React router dom ) if you are:

- using Next/Router
- Run Next build and export

**Comment by mlynch** [comment]
@AlexcastroDev thanks, PRs always welcome and appreciated. However, without Ionic Router you're not getting native style page transitions, right? That's a pretty important detail for shipping these apps to the app stores.

**Comment by mlynch** [comment]
I've got a WIP branch after running the cap migrate command that seems to work but something is up with routing in the app that I want to fix first. See #37

**Comment by mlynch** [comment]
Done in 3abbd0b490a324d3de4b920e13611356a7af849a
