### ISSUE TITLE
How to make the next/image work?

### ISSUE THREAD

**Issue by vader1359** [mlynch/nextjs-tailwind-ionic-capacitor-starter#32]
I'm trying to setup a Capacitor on a Next.js project. I cannot use the Next.js Image Optimization as whenever I export it I will see the error below. But in this repo, we can still use next/image normally. How can it be?
```
info  - No "exportPathMap" found in "/Users/iant1359/Develop/learn/capacitor-next/next.config.js". Generating map from "./pages"
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Configure `images.unoptimized = true` in `next.config.js` to disable the Image Optimization API.
  Read more: https://nextjs.org/docs/messages/export-image-api
    at /Users/iant1359/Develop/learn/capacitor-next/node_modules/next/dist/export/index.js:150:23
    at async Span.traceAsyncFn (/Users/iant1359/Develop/learn/capacitor-next/node_modules/next/dist/trace/trace.js:79:20)
```

**Comment by mlynch** [comment]
When the next app runs in capacor it is running as a static site, which means it only works with next apps that can be exported. There’s no node/JS server running in the app, so no Next features that run on the server will work.

The alternative if you must have those features is to load the app remotely as a web app. There are two ways to do that: use the `server.url` config option in capacitor to point to a remote server, or use Ionic Portals and load your app as a micro-frontend experience: https://ionic.io/portals

**Comment by vader1359** [comment]
Hello, thank you for your quick answer. I understand how only the static site works on Capacitor but I don't get how I don't get the above error when I build this starter project. For example, here for example, the Feed component:
```import Image from 'next/image';
import Card from '../ui/Card';

import {
  IonPage,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonButtons,
  IonButton,
  IonIcon,
  IonContent,
  IonMenuButton,
} from '@ionic/react';
import Notifications from './Notifications';
import { useState } from 'react';
import { notificationsOutline } from 'ionicons/icons';
import { getHomeItems } from '../../store/selectors';
import Store from '../../store';

const FeedCard = ({ title, type, text, author, authorAvatar, image }) => (
  <Card className="my-4 mx-auto">
    <div className="h-32 w-full relative">
      <Image className="rounded-t-xl" objectFit="cover" src={image} alt="" layout='fill' />
    </div>```
