### ISSUE TITLE
CSS not working on ios build

### ISSUE THREAD

**Issue by AbdulQadir0731** [mlynch/nextjs-tailwind-ionic-capacitor-starter#35]

**Comment by AbdulQadir0731** [comment]
![Simulator Screen Shot - iPhone 13 mini - 2022-09-30 at 05 54 03](https://user-images.githubusercontent.com/45762022/193167096-2df21f88-769a-45b3-8c44-3c2d6d32b068.png)

**Comment by mlynch** [comment]
Unable to reproduce. If you could try connecting to your app with Safari and sharing the logs that would be helpful
