### ISSUE TITLE
Dark mode in browser not in apk

### ISSUE THREAD

**Issue by JamesDAdams** [mlynch/nextjs-tailwind-ionic-capacitor-starter#38]
Hi,

in my browser or android emulator per default i have the dark mod but not in the apk why ?

Emulator :
![image](https://user-images.githubusercontent.com/20860324/193467455-b973f9cf-d5c8-4b7c-a05f-e7030035e082.png)

APK : 
![image](https://user-images.githubusercontent.com/20860324/193467479-fa5a0cff-df9f-4485-8f90-8098d7a97f38.png)

**Comment by mlynch** [comment]
You're sure the device running the apk is in dark mode? If so, then I'm not sure, would need to check around
