### ISSUE TITLE
next export and NextJS 13

### ISSUE THREAD

**Issue by RobSchilderr** [mlynch/nextjs-tailwind-ionic-capacitor-starter#41]
So, yesterday, [Next.js 13](https://nextjs.org/blog/next-13) was released with a first beta preview of React Server Components enabled by default. It's a big deal, and it appears that server and client integration is becoming even more entwined.

I'm curious whether we'll be able to use `next export` in the future to create Capacitor/Next.js projects the same way we do here. What would it mean if they stopped supporting `next export`? Is it even worth using Next.js 13 with Capacitor right now?

It would be fantastic if there was a blog post or an answer to this, as it determines whether it is still worthwhile to use Next.js or Capacitor to build our apps. 

I'm guessing it's relevant to this repository because you guys try to keep the packages up to date here. Thanks for reading this issue and I hope this is the right place to discuss this.

**Comment by ZhymonNorman** [comment]
@RobSchilderr i was hoping for this as well, sadly Next 13 doesn't support `next export` at this time however it is on the roadmap seen [here](https://beta.nextjs.org/docs/app-directory-roadmap#planned-features)

**Comment by mlynch** [comment]
This would be a question for the Next.js team. My understanding is the standard `next export` continues to work in Next 13, just not in the new `app` directory features

**Comment by taig** [comment]
Static export for app directory just landed in canary https://beta.nextjs.org/docs/configuring/static-export

**Comment by RobSchilderr** [comment]
> https://beta.nextjs.org/docs/configuring/static-export

now that is sick! Anyone tested it yet?

**Comment by vader1359** [comment]
Is there any update on this matter?

**Comment by RobSchilderr** [comment]
> Is there any update on this matter?

yeah `next export` is added, so you could in theory use the new `/app` router, but you'd have to use a lot of `use client` I guess. I know people are busy with it, you can find them in the Capacitor Discord.

**Comment by vader1359** [comment]
@RobSchilderr The last time I tried when the next export released I still cannot make it work, and it's a bit overwhelming for me to fix the errors. Do you have plan to add it to your Supertoken repo or any example some succesfully match this?

**Comment by RobSchilderr** [comment]
> @RobSchilderr The last time I tried when the next export released I still cannot make it work, and it's a bit overwhelming for me to fix the errors. Do you have plan to add it to your Supertoken repo or any example some succesfully match this?

No as far as I know there is not any example out there.

**Comment by nathanchapman** [comment]
Resolved in #55
