### ISSUE TITLE
Convert this repo to Template repository

### ISSUE THREAD

**Issue by vltansky** [mlynch/nextjs-tailwind-ionic-capacitor-starter#49]
I think this would be easier to use as a starter kit
https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template

examples (just random, from first google results):
https://github.com/fastly/compute-starter-kit-javascript-default
https://github.com/textbook/starter-kit

**Comment by nathanchapman** [comment]
I agree this would be a nice change
@mlynch we may need your help on this one since it requires an update in the settings

**Comment by mlynch** [comment]
Try now

**Comment by nathanchapman** [comment]
@mlynch Perfect!
<img width="402" alt="image" src="https://github.com/mlynch/nextjs-tailwind-ionic-capacitor-starter/assets/4032071/2c8d92a8-85f4-4f94-9f83-618409eecb66">
