### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by mlynch** [mlynch/nextjs-tailwind-ionic-capacitor-starter#51]
Hi, I'm no longer working on this project. If anyone is interested in taking it over and maintaining it let me know!

**Comment by nathanchapman** [comment]
@mlynch I'd be happy to start with getting #39 into a mergable state, then work on upgrading to Next 14

**Comment by leog** [comment]
also offering help @mlynch @nathanchapman 
I love the prospects of this project

**Comment by mlynch** [comment]
Thanks y'all! I'll add you as maintainers

**Comment by CharlesOnAir** [comment]
@mlynch It's ok ? @leog and @nathanchapman are maintainers ?
When will you be releasing the Typescript version of the project?

**Comment by mlynch** [comment]
@nathanchapman @leog invites sent!

**Comment by nathanchapman** [comment]
thank you @mlynch!
