### ISSUE TITLE
New app router errors

### ISSUE THREAD

**Issue by alexei-petru** [mlynch/nextjs-tailwind-ionic-capacitor-starter#58]
With new app routing navigating by url  dosent work and give error.
<img width="417" alt="Screenshot 2024-03-06 at 00 28 13" src="https://github.com/mlynch/nextjs-tailwind-ionic-capacitor-starter/assets/76633311/8a21c5e8-c200-4947-9c92-7108794cad89">

It partially works if I change like this, but still give an error,
<img width="461" alt="Screenshot 2024-03-06 at 00 31 41" src="https://github.com/mlynch/nextjs-tailwind-ionic-capacitor-starter/assets/76633311/045418c4-d470-44a9-98a3-4e87d8b919c2">

<img width="999" alt="image" src="https://github.com/mlynch/nextjs-tailwind-ionic-capacitor-starter/assets/76633311/31001849-8b40-4fb0-8907-43faaec13075">

Does anybody how to fix it?

**Comment by nathanchapman** [comment]
@alexei-petru thanks for pointing this out. Looking into a fix!

**Comment by alexei-petru** [comment]
Thank you for fast fix, you are the best.
There are two more warnings, should I ignore them? Does anybody know why and how to fix them? I have searched for a solution and could not find one.
<img width="408" alt="image" src="https://github.com/mlynch/nextjs-tailwind-ionic-capacitor-starter/assets/76633311/98eaa38d-6586-4a1b-a99a-a94816e41cd4">
<img width="1203" alt="Screenshot 2024-03-09 at 22 47 35" src="https://github.com/mlynch/nextjs-tailwind-ionic-capacitor-starter/assets/76633311/3126d117-a7f8-475e-b6af-df2ad3bef64d">

**Comment by nathanchapman** [comment]
I noticed these as well, but they did seem like just warnings and not actually affecting anything. If you see otherwise, please let me know! I'll keep trying to figure out a better long term solution as well. It's pretty strange in its current state 😅
