### ISSUE TITLE
No transition when navigating from Lists to ListDetail

### ISSUE THREAD

**Issue by doender** [mlynch/nextjs-tailwind-ionic-capacitor-starter#6]
Thnx for this repo! I saw an issue where navigating from `Lists` to a `ListDetail` page causes a refresh.

**Comment by mlynch** [comment]
Oh thanks, will take a look at that, forgot about that route 👀

**Comment by mlynch** [comment]
I also just fixed another issue related to this that was causing the transition to not look good. Had some bad CSS from the first version of this.
