### ISSUE TITLE
CANNOT RUN ON ANDROID

### ISSUE THREAD

**Issue by cstory1** [mlynch/nextjs-tailwind-ionic-capacitor-starter#62]
`npm run android`

> nextjs-tailwind-ionic-capacitor-starter@5.0.0 android
> npx cap run android

✔ Copying web assets from out to android/app/src/main/assets/public in 188.01ms
✔ Creating capacitor.config.json in android/app/src/main/assets in 7.11ms
⠴ copy android [info] Inlining sourcemaps
✔ copy android in 331.26ms
✔ Updating Android plugins in 40.85ms
[info] Found 1 Capacitor plugin for android:
       @capacitor/status-bar@5.0.7
✔ update android in 237.44ms
[error] SyntaxError: Unexpected token 'E', "ERR_SUBPRO"... is not valid JSON
        at JSON.parse (<anonymous>)
        at getPlatformTargets
        (/home/tobi/Documents/development/nextjs-tailwind-ionic-capacitor-starter/node_modules/@capacitor/cli/dist/util/native-run.js:39:26)
        at process.processTicksAndRejections
        (node:internal/process/task_queues:95:5)
        at async runAndroid
        (/home/tobi/Documents/development/nextjs-tailwind-ionic-capacitor-starter/node_modules/@capacitor/cli/dist/android/run.js:14:64)
        at async run
        (/home/tobi/Documents/development/nextjs-tailwind-ionic-capacitor-starter/node_modules/@capacitor/cli/dist/tasks/run.js:107:9)
        at async runCommand
        (/home/tobi/Documents/development/nextjs-tailwind-ionic-capacitor-starter/node_modules/@capacitor/cli/dist/tasks/run.js:81:13)
        at async
        /home/tobi/Documents/development/nextjs-tailwind-ionic-capacitor-starter/node_modules/@capacitor/cli/dist/index.js:129:9
        at async
        /home/tobi/Documents/development/nextjs-tailwind-ionic-capacitor-starter/node_modules/@capacitor/cli/dist/telemetry.js:26:13
        at async Command.<anonymous>
        (/home/tobi/Documents/development/nextjs-tailwind-ionic-capacitor-starter/node_modules/@capacitor/cli/dist/util/cli.js:12:13)

**Comment by nathanchapman** [comment]
@tobiadiks
I'm unable to reproduce this without more information.
Are you running the correct version of Android Studio, gradle, and JDK? Have you run `npm install`?
https://capacitorjs.com/docs/updating/5-0#upgrade-android-studio

**Comment by cstory1** [comment]
I found out this happens when I am using Android Studio installed via snap on Linux.

Successfully ran it  by opening android studio directly and opening the android folder.
