### ISSUE TITLE
Local Storage or Database Options? Prisma support?

### ISSUE THREAD

**Issue by fyroc** [mlynch/nextjs-tailwind-ionic-capacitor-starter#8]
I'm moving my current app to React (Next.js) and looking for Cordova alternatives and stumbled upon this repo. The only thing it's missing is some sort of local storage options. Would this be able to work with Prisma so I could use SQLite for local storage on mobile apps?

**Comment by mlynch** [comment]
Not sure about Prisma but you can use any mobile storage technology in this app. In-browser ones, sqlite, other fancy ones I've never heard of 😅 you can do anything you want
